export const languages = [
  { value: "en", label: "English", market: "usa" },
  { value: "fi", label: "Finnish", market: "finland" },
  { value: "de", label: "German", market: "germany" },
  // { value: "es", label: "Spanish", market: "global" },
  // { value: "fr", label: "French", market: "global" },
  // { value: "it", label: "Italian", market: "global" },
  // { value: "pt", label: "Portuguese", market: "global" },
  // { value: "ru", label: "Russian", market: "global" },
  // { value: "zh", label: "Chinese (Mandarin)", market: "global" },
  // { value: "ja", label: "Japanese", market: "global" },
  // { value: "ko", label: "Korean", market: "global" },
  // { value: "ar", label: "Arabic", market: "global" },
  // { value: "hi", label: "Hindi", market: "global" },
  // { value: "bn", label: "Bengali", market: "global" },
  // { value: "ur", label: "Urdu", market: "global" },
  // { value: "tr", label: "Turkish", market: "global" },
  // { value: "vi", label: "Vietnamese", market: "global" },
  // { value: "fa", label: "Persian (Farsi)", market: "global" },
  // { value: "ms", label: "Malay / Indonesian", market: "global" },
  // { value: "th", label: "Thai", market: "global" },
  // { value: "he", label: "Hebrew", market: "global" },
  // { value: "nl", label: "Dutch", market: "global" },
  // { value: "sv", label: "Swedish", market: "global" },
  // { value: "pl", label: "Polish", market: "global" },
  // { value: "uk", label: "Ukrainian", market: "global" },
  // { value: "el", label: "Greek", market: "global" },
] as const;

export type LanguageCode = typeof languages[number]['value'];
export type Market = "finland" | "germany" | "usa" | "global";